### ISSUE TITLE
12. Add MileStone / Edit MileStone

### ISSUE THREAD

**Issue by rnfxl92** [boostcamp-2020/IssueTracker-12#62]
- [x] pop up 형태로 구성
- [x] 수정 시, 기존 저장 내용 보여주기
- [x] 화면 구성
	- [x] 제목
	- [x] 완료 날짜 (선택 사항. 안 넣어도 돼야 함)
		- [x] yyyy-mm-dd 형식에 맞는 문자열인지 판단
		- [x] 형식에 맞지 않는 경우 “완료날짜” 라벨을 빨간색으로 표시
	- [x] 설명 (선택 사항. 안 넣어도 돼야 함)
	- [x] 초기화 버튼 누르면 입력한 값 모두 초기화
	- [x] 저장 버튼 투르면 입력한 값 저장
	- [x] x 버튼 누르면, 조건 없이 화면 닫기
